site_name: Byte Varnish Cluster Instructies
docs_dir: doc
pages:
- [intro.md, Intro]
- [joomla.md, Joomla]
- [drupal.md, Drupal]
- [wordpress.md, Wordpress]
- [customcms.md, Custom CMS]
- [faq.md, FAQ]
